baseurl = "https://rliebz.github.io/hugo-pages-test/"
languageCode = "en-us"
title = "tusk"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true

[params]
	# General information
	author = "Robert Liebowitz"
	description = "A modern task runner"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/rliebz/tusk"

	version = "dev"
	logo = ""
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
	primary = "teal"
	accent  = "deep-orange"

	[params.font]
	text = "Ubuntu"
	code = "Ubuntu Mono"


[social]
	github  = "rliebz"
	email   = "rliebz@gmail.com"


[[menu.main]]
	name   = "Getting Started"
	url    = "/"
